In [ ]:
import numpy as np

In [4]:
#create array using np
#create 1d array
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [8]:
arr2 = np.array([1,2,3,4,5,6])
arr2 = arr2.reshape(2,3)
print(arr2)

[[1 2 3]
 [4 5 6]]


In [10]:
arr2 = np.array([[1,2,3,4]])
print(arr2.shape)

(1, 4)


In [14]:
arr = np.arange(0,10,2).reshape(5,1)
print(arr)

[[0]
 [2]
 [4]
 [6]
 [8]]


In [15]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
#identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Attributes of numpy array
arr = np.array([[1,2,3],[4,5,6]])
print("Arr: \n",arr)
print("Shape: ",arr.shape)
print("Number of dimensions",arr.ndim)
print("Number of elements",arr.size)
print("Datatype",arr.dtype)
print("Itemsize in bytes",arr.itemsize)

Arr: 
 [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Number of dimensions 2
Number of elements 6
Datatype int64
Itemsize in bytes 8


In [19]:
#Numpy vectorized operations
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

###element wise addition
print("Addition:", arr1+arr2)

###element wise subtraction
print("Subtraction", arr1-arr2)

###element wise multiplication
print("Multiplication", arr1*arr2)

###element wise division
print("Division", arr1/arr2)




Addition: [11 22 33 44 55]
Subtraction [ -9 -18 -27 -36 -45]
Multiplication [ 10  40  90 160 250]
Division [0.1 0.1 0.1 0.1 0.1]


In [22]:
#Universal functions
arr = np.array([2,3,4,5,6])
##sqaure root
print(np.sqrt(arr))

##exponential
print(np.exp(arr))

##sine
print(np.sin(arr))

##natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [25]:
#Array slicing and indexing
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Arr: \n",arr)

Arr: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [28]:
print(arr[0])
print(arr[0][1])

[1 2 3 4]
2


In [30]:
arr[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
print(arr[1:,2:])
print(arr[0:2,2:])
print(arr[1:,1:3])

[[ 7  8]
 [11 12]]
[[3 4]
 [7 8]]
[[ 6  7]
 [10 11]]


In [34]:
##modify array elements
arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [35]:
arr[1:] = 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [38]:
##statistical concept -- normalization
## to have a mean of 0 and standard deviation of 1
data = np.array([1,2,3,4,5])
mean = np.mean(data)
print("Mean",mean)
std_dev = np.std(data)
print("Standard Deviation",std_dev)
variance = np.var(data) 
print("Variance",variance)
median = np.median(data)
print("Median",median)

normalized_data = (data - mean) /std_dev
print("Normalized Data:",normalized_data)

Mean 3.0
Standard Deviation 1.4142135623730951
Variance 2.0
Median 3.0
Normalized Data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [45]:
##Logical operations
data = np.array([1,2,3,4,5,6,7,8,9,10])
print(data > 5)

print(data[data>5])
print(data[(data >=5) & (data <=8)])


[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[5 6 7 8]
